baseURL = 'https://review-him.github.io/'
languageCode = 'en-us'
title = 'Review Him Blog'
theme = 'monday-theme'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[module.mounts]]
source = 'images'
target = 'static/images'

